version: '3'

services:
  ml_api_python:
    build: ml_api_python
    tty: true
    ports:
      - "5000:5000"
    command: python3.7 app.py

  ml_api_r:
    build: ml_api_r
    tty: true
    ports:
      - "6100:6100"
    command: Rscript app/app.R

  ml_api_julia:
    build: ml_api_julia
    tty: true
    ports:
      - "7000:7000"
    command: julia app/app.jl

  server:
    build: server
    tty: true
    ports:
      - "8080:8080"
    command: bash -c "cd src && go run server.go"

